services:

  frontend:
    build:
      context: ./FrontendBlog
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    env_file:
      - ./FrontendBlog/.env
    depends_on:
      - backend
    networks:
      - blog-net
    restart: unless-stopped

  backend:
    build:
      context: ./BackendBlog12
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SUPABASE_DB_URL: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres?sslmode=require
      SUPABASE_DB_USER: postgres.oobzklsqvdsnvdseyske
      SUPABASE_DB_PASSWORD: EC2cdSYLC7nKK3TD
    networks:
      - blog-net
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: blog-jenkins
    environment:
      JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/workspace/blog:ro
    networks:
      - blog-net
    restart: unless-stopped

networks:
  blog-net:
    driver: bridge

volumes:
  jenkins_home: